import json
from elasticsearch import Elasticsearch
from pymongo import MongoClient
from bson import json_util

def parse_json(data):
    return json.loads(json_util.dumps(data))

db = MongoClient("mongodb://localhost:27017")
dbName = db["Velib"]
collName = dbName["velo_libre_1728482647"]

# Password for the 'elastic' user generated by Elasticsearch
ELASTIC_PASSWORD = "6mZByQl=UvxRGUty1I4i"

# Create the client instance
client = Elasticsearch(
    "https://localhost:9200",
    ca_certs="http_ca.crt",
    basic_auth=("elastic", ELASTIC_PASSWORD)
)

# Successful response!
client.info()

docu = collName.find()

for doc in docu:
    doc_json = parse_json(doc)
    doc_json_id = doc_json.pop("_id")
    client.index(index="velib", id=doc_json_id, body=doc_json)

print("Indexation terminée.")
# {'name': 'instance-0000000000', 'cluster_name': ...}